FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["taskiq", "worker", "src.tasks.broker:broker", "src.tasks.scheduler.hold_task", "src.tasks.scheduler.upload_task", "src.tasks.scheduler.booking_task"]